---
  
- name: Fix dpkg
  shell: "dpkg --configure -a"

- name: Update All Packages
  apt:
    name: "*"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    state: latest
  register: reboot_node

- name: Reboot system if required
  when: reboot_node is changed
  reboot:
    post_reboot_delay: 180
    reboot_timeout: 900
