---
  
- name: Fix dpkg
  shell: "dpkg --configure -a"

- name: Update All Packages
  apt:
    name: "*"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    state: latest

- name: Reboot system if required
  command: shutdown -r now 'Rebooting to complete system upgrade'
    removes=/var/run/reboot-required

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
